
import account.HoaDon;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import servicecuaHa.ServiceH;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC
 */
public class ThongKe extends javax.swing.JFrame {

    ServiceH serviceH;
    DefaultTableModel defaultTableModelTTKH;
    DefaultTableModel defaultTableModelTK;
    String lenh;

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        serviceH = new ServiceH();
        defaultTableModelTTKH = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableChiTiet.setModel(defaultTableModelTTKH);

        defaultTableModelTTKH.addColumn("Ngày Tạo");
        defaultTableModelTTKH.addColumn("Tên Quận");
        defaultTableModelTTKH.addColumn("Tổng Tiêu Thụ");
        
        lenh = "select ngaytao, tenquan, sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, khachhang as kh, (select ngaytaohd as ngaytao, idhd from tblhoadon) as tam  where hd.makh=kh.makh and tam.idhd=hd.idhd group by tenquan, ngaytao";
        setDataThongKe3(serviceH.getAllHoaDon(lenh));
        
        defaultTableModelTK = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableTongTien.setModel(defaultTableModelTK);

        defaultTableModelTK.addColumn("Thời Gian");
        defaultTableModelTK.addColumn("Tổng Tiêu Thụ");
        lenh = "select ngaytao, ngaytao as tenquan,sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, (select ngaytaohd as ngaytao, idhd from tblhoadon) as tam  where  tam.idhd=hd.idhd group by ngaytao";
        setDataThongKe2(serviceH.getAllHoaDon(lenh));

    }

    //table thống kê
    private void setDataThongKe2(List<HoaDon> khachHangs) {
        for (HoaDon khachHang : khachHangs) {
            defaultTableModelTK.addRow(new Object[]{khachHang.getNgaytao(), khachHang.getTong()});
        }
    }

    private void setDataThongKe3(List<HoaDon> khachHangs) {
        for (HoaDon khachHang : khachHangs) {
            defaultTableModelTTKH.addRow(new Object[]{khachHang.getNgaytao(), khachHang.getTenquan(), khachHang.getTong()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ClearTK = new javax.swing.JButton();
        dsThongKe = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTongTien = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableChiTiet = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 102, 51));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setBackground(new java.awt.Color(255, 102, 102));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 51));
        jLabel12.setText("THỐNG KÊ");

        ClearTK.setBackground(new java.awt.Color(255, 102, 0));
        ClearTK.setText("Làm mới");
        ClearTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTKActionPerformed(evt);
            }
        });

        dsThongKe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dsThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thành Phố Đà Nẵng", "Thống Kê Theo Tháng", "Thống Kê Theo Năm", " ", " " }));
        dsThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsThongKeActionPerformed(evt);
            }
        });

        tableTongTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTongTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTongTienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableTongTien);

        tableChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableChiTiet);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(dsThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(ClearTK, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(dsThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(ClearTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs_QLTD/tien.png"))); // NOI18N

        back2.setBackground(new java.awt.Color(255, 255, 255));
        back2.setText("Trở lại");
        back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(842, 842, 842))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(back2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTKActionPerformed
        // TODO add your handling code here:
        defaultTableModelTTKH.setRowCount(0);
        
        defaultTableModelTK.setRowCount(0);
    }//GEN-LAST:event_ClearTKActionPerformed

    private void dsThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsThongKeActionPerformed
        // TODO add your handling code here:
        String loai = String.valueOf(dsThongKe.getSelectedItem());
        switch (loai) {
            case "Thành Phố Đà Nẵng":
                lenh = "select ngaytao, ngaytao as tenquan,sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, (select ngaytaohd as ngaytao, idhd from tblhoadon) as tam  where  tam.idhd=hd.idhd group by ngaytao";
                defaultTableModelTK.setRowCount(0);
                setDataThongKe2(serviceH.getAllHoaDon(lenh));
                break;
            case "Thống Kê Theo Tháng":
                lenh = "select ngaytao, ngaytao as tenquan,sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, (select concat(month(ngaytaohd),'/',year(ngaytaohd)) as ngaytao, idhd from tblhoadon) as tam  where  tam.idhd=hd.idhd group by ngaytao";
                defaultTableModelTK.setRowCount(0);
                setDataThongKe2(serviceH.getAllHoaDon(lenh));
                break;
            case "Thống Kê Theo Năm":
                lenh = "select ngaytao, ngaytao as tenquan, sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, (select year(ngaytaohd) as ngaytao, idhd from tblhoadon) as tam  where  tam.idhd=hd.idhd group by ngaytao";
                defaultTableModelTK.setRowCount(0);
                setDataThongKe2(serviceH.getAllHoaDon(lenh));
                break;
        }
    }//GEN-LAST:event_dsThongKeActionPerformed

    private void tableTongTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTongTienMouseClicked
        // TODO add your handling code here:
        int row = tableTongTien.getSelectedRow();
        String tg = String.valueOf(tableTongTien.getValueAt(row, 0));
        String loai = String.valueOf(dsThongKe.getSelectedItem());
        switch (loai) {
            case "Thành Phố Đà Nẵng":
                lenh = "select ngaytao, tenquan, sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, khachhang as kh, (select ngaytaohd as ngaytao, idhd from tblhoadon) as tam  where hd.makh=kh.makh and tam.idhd=hd.idhd and ngaytao = '"+tg+"' group by tenquan, ngaytao";
                defaultTableModelTTKH.setRowCount(0);
                setDataThongKe3(serviceH.getAllHoaDon(lenh));
                break;
            case "Thống Kê Theo Tháng":
                lenh = "select ngaytao, tenquan, sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, khachhang as kh, (select concat(month(ngaytaohd),'/',year(ngaytaohd)) as ngaytao, idhd from tblhoadon) as tam  where hd.makh=kh.makh and tam.idhd=hd.idhd and ngaytao = '"+tg+"' group by tenquan, ngaytao ";
                defaultTableModelTTKH.setRowCount(0);
                setDataThongKe3(serviceH.getAllHoaDon(lenh));
                break;
            case "Thống Kê Theo Năm":
                lenh = "select ngaytao, tenquan, sum(tongtiendien+tongtiennuoc) as tong from tblhoadon as hd, khachhang as kh, (select year(ngaytaohd) as ngaytao, idhd from tblhoadon) as tam  where hd.makh=kh.makh and tam.idhd=hd.idhd  and ngaytao = '"+tg+"' group by tenquan, ngaytao";
                defaultTableModelTTKH.setRowCount(0);
                setDataThongKe3(serviceH.getAllHoaDon(lenh));
                break;
        }

    }//GEN-LAST:event_tableTongTienMouseClicked

    private void back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseClicked
        // TODO add your handling code here:
        new TrangChuNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearTK;
    private javax.swing.JButton back2;
    private javax.swing.JComboBox<String> dsThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableChiTiet;
    private javax.swing.JTable tableTongTien;
    // End of variables declaration//GEN-END:variables
}
