
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ketnoiSQL.JDBCConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class TinhTienDien extends javax.swing.JFrame {

    /**
     * Creates new form TinhTienDien
     */
    DefaultTableModel tblModel = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }
    };
    PreparedStatement ps;
    ResultSet rs, rsKH;
    Vector vec, vecKH;
    Connection connect = JDBCConnection.getJDBCConnection();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    java.util.Date date = new java.util.Date();

    public TinhTienDien() {
        initComponents();
        tblModel.addColumn("Mã Tiêu thụ");
        tblModel.addColumn("Mã khách hàng");
        tblModel.addColumn("Tên khách hàng");
        tblModel.addColumn("Địa chỉ");
        tblModel.addColumn("Số điện thoại");
        tblModel.addColumn("Chỉ số điện cũ");
        tblModel.addColumn("Chỉ nước điện cũ");
        tblCSD.setModel(tblModel);
        txtNgayNhap.setText(dateFormat.format(date));
        ReloadTbl();
    }

    public void ReloadTbl() {
        tblModel.getDataVector().removeAllElements();
        //select theo khách hàng VIP
        try {
            ps = connect.prepareStatement("select IdTT,tblSotieuthu.MaKH,TenKH,DiaChi,SDT,chisocuDien,chisocuNuoc from tblSotieuthu join KhachHang on KhachHang.MaKH=tblSotieuthu.MaKH  ");
            rs = ps.executeQuery();
            while (rs.next()) {
                vec = new Vector();
                vec.add(rs.getString("IdTT"));
                vec.add(rs.getString("MaKH"));
                vec.add(rs.getString("TenKH"));
                vec.add(rs.getString("DiaChi"));
                vec.add(rs.getString("SDT"));
                vec.add(rs.getDouble("chisocuDien"));
                vec.add(rs.getDouble("chisocuNuoc"));
                tblModel.addRow(vec);
            }
            tblCSD.setModel(tblModel);
            btnLuu.setEnabled(false);
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    ;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCSNC = new javax.swing.JTextField();
        txtCSDM = new javax.swing.JTextField();
        LB1 = new javax.swing.JLabel();
        txtCSNM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCSD = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnXuatHD = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        txtMTT = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtCSDC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTienDien = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTienNuoc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSTTD = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtSTTN = new javax.swing.JTextField();
        btnTinhTien = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(986, 660));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(807, 611));

        txtCSNC.setEnabled(false);
        txtCSNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSNCActionPerformed(evt);
            }
        });

        txtCSDM.setEnabled(false);
        txtCSDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSDMActionPerformed(evt);
            }
        });

        LB1.setBackground(new java.awt.Color(255, 102, 102));
        LB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LB1.setForeground(new java.awt.Color(255, 102, 51));
        LB1.setText("TÍNH TIỀN ĐIỆN");

        txtCSNM.setEnabled(false);
        txtCSNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSNMActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 51));
        jLabel10.setText("Mã khách hàng:");

        tblCSD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblCSD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCSDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCSD);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 51));
        jLabel11.setText("Tên khách hàng:");

        btnLuu.setBackground(new java.awt.Color(255, 102, 0));
        btnLuu.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXuatHD.setBackground(new java.awt.Color(255, 102, 0));
        btnXuatHD.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        btnXuatHD.setText("Xuất hóa đơn");
        btnXuatHD.setEnabled(false);
        btnXuatHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHDActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 51));
        jLabel14.setText("Mã tiêu thụ:");

        btnDangXuat.setBackground(new java.awt.Color(255, 102, 0));
        btnDangXuat.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        txtMTT.setEnabled(false);
        txtMTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMTTActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 102, 0));
        btnThoat.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtNgayNhap.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("Ngày nhập:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 51));
        jLabel12.setText("Địa chỉ:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 51));
        jLabel13.setText("Số điện thoại:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 51));
        jLabel15.setText("Chỉ số điện cũ:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 51));
        jLabel16.setText("Chỉ số nước cũ:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 51));
        jLabel17.setText("Chỉ số điện mới:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 51));
        jLabel18.setText("Chỉ số nước mới:");

        txtMKH.setEnabled(false);

        txtTenKH.setEnabled(false);
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        txtDiaChi.setEnabled(false);
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtSDT.setEnabled(false);
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtCSDC.setEnabled(false);
        txtCSDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSDCActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 51));
        jLabel19.setText("Tiền điện:");

        txtTienDien.setEnabled(false);
        txtTienDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienDienActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 51));
        jLabel20.setText("Tiền nước:");

        txtTienNuoc.setEnabled(false);
        txtTienNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienNuocActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 102, 51));
        jLabel21.setText("Số điện tiêu thụ:");

        txtSTTD.setEnabled(false);
        txtSTTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTTDActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 51));
        jLabel22.setText("Số nước tiêu thụ:");

        txtSTTN.setEnabled(false);
        txtSTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTTNActionPerformed(evt);
            }
        });

        btnTinhTien.setBackground(new java.awt.Color(255, 102, 0));
        btnTinhTien.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        btnTinhTien.setText("Tính tiền");
        btnTinhTien.setEnabled(false);
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 102, 0));
        btnReset.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LB1)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTinhTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDangXuat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMTT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCSDC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCSNC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtMKH, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCSDM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCSNM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSTTD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSTTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienDien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienNuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMTT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCSDC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCSNC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCSDM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCSNM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSTTD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSTTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTienDien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTienNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs_QLTD/tinhtien.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCSNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSNCActionPerformed

    private void txtCSDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSDMActionPerformed

    private void txtCSNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSNMActionPerformed

    private void tblCSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCSDMouseClicked
        // TODO add your handling code here:
        String DepName = null;
        int line = tblCSD.getSelectedRow();
        String MaTT = (String) tblModel.getValueAt(line, 0);
        String MaKH = (String) tblModel.getValueAt(line, 1);
        String TenKH = (String) tblModel.getValueAt(line, 2);
        String DiaChi = (String) tblModel.getValueAt(line, 3);
        String SDT = (String) tblModel.getValueAt(line, 4);
        String chisocuDien = tblModel.getValueAt(line, 5).toString();
        String chisocuNuoc = tblModel.getValueAt(line, 6).toString();

        //gan du lieu vao textfile
        txtMTT.setText(MaTT);
        txtMKH.setText(MaKH);
        txtTenKH.setText(TenKH);
        txtDiaChi.setText(DiaChi);
        txtSDT.setText(SDT);
        txtCSDC.setText(chisocuDien);
        txtCSNC.setText(chisocuNuoc);
        btnTinhTien.setEnabled(true);
        btnLuu.setEnabled(false);
        btnXuatHD.setEnabled(false);
        txtCSDM.setEnabled(true);
        txtCSNM.setEnabled(true);
        txtCSDM.setText("");
        txtCSNM.setText("");
        txtSTTD.setText("");
        txtSTTN.setText("");
        txtTienDien.setText("");
        txtTienNuoc.setText("");

    }//GEN-LAST:event_tblCSDMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu không?");
        if (click == 0) {

            try {

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            try {
                ps = connect.prepareStatement("update tblSotieuthu set chisocuDien =?,chisocuNuoc =? where IdTT=?");
                ps.setString(3, txtMTT.getText());
                ps.setString(1, txtCSDM.getText());
                ps.setString(2, txtCSNM.getText());
                ps.executeUpdate();
                ps = connect.prepareStatement("insert into tblHoaDon values(?,?,?,?,?,?,convert(varchar, getdate(), 111))");
                ps.setString(1, txtMKH.getText());
                ps.setString(2, txtTenKH.getText());
                ps.setString(3, txtSTTD.getText());
                ps.setString(4, txtSTTN.getText());
                ps.setString(5, txtTienDien.getText());
                ps.setString(6, txtTienNuoc.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Lưu thành công ! ");
                tblModel.getDataVector().removeAllElements();
                ReloadTbl();
                btnXuatHD.setEnabled(true);
            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void txtMTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMTTActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtCSDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSDCActionPerformed

    private void txtTienDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienDienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienDienActionPerformed

    private void txtTienNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienNuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienNuocActionPerformed

    private void txtSTTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTTDActionPerformed

    private void txtSTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTTNActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        // TODO add your handling code here:
        while (true) {
            if (txtCSDM.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Chỉ số điện mới không được để trống");
                txtCSDM.grabFocus();
                return;
            } else if (!txtCSDM.getText().trim().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Chỉ số điện mới phải là số và lớn hơn 0");
                txtCSDM.grabFocus();
                return;
            } else if ((Double.parseDouble(txtCSDM.getText())) < (Double.parseDouble(txtCSDC.getText()))) {
                JOptionPane.showMessageDialog(this, "Chỉ số điện mới phải lớn hơn chỉ số điện cũ");
                txtCSDM.grabFocus();
                return;
            } else {
                break;
            }
        }
        while (true) {
            if (txtCSNM.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Chỉ số nước mới không được để trống");
                txtCSNM.grabFocus();
                return;
            } else if (!txtCSNM.getText().trim().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Chỉ số nước mới phải là số và lớn hơn 0");
                txtCSNM.grabFocus();
                return;
            } else if ((Double.parseDouble(txtCSNM.getText())) < (Double.parseDouble(txtCSNC.getText()))) {
                JOptionPane.showMessageDialog(this, "Chỉ số nước mới phải lớn hơn chỉ số nước cũ");
                txtCSNM.grabFocus();
                return;
            } else {
                break;
            }
        }

        try {
            Double dm, dc, nm, nc, ttd, ttn;
            dm = Double.parseDouble(txtCSDM.getText());
            dc = Double.parseDouble(txtCSDC.getText());
            nm = Double.parseDouble(txtCSNM.getText());
            nc = Double.parseDouble(txtCSNC.getText());
            ttd = dm - dc;
            ttn = nm - nc;
            txtSTTD.setText(ttd.toString());
            txtSTTN.setText(ttn.toString());
            txtTienDien.setText((TinhTienDien(ttd)));
            txtTienNuoc.setText(TinhTienNuoc(ttn));
        } catch (Exception e) {
        }
        btnTinhTien.setEnabled(false);
        btnLuu.setEnabled(true);
        txtCSDM.setEnabled(false);
        txtCSNM.setEnabled(false);
    }//GEN-LAST:event_btnTinhTienActionPerformed
    public String TinhTienDien(Double csd) {
        Double t = 0.0;
        int i = 0;
        Double giadien[] = new Double[10];
        try {
            ps = connect.prepareStatement("select * from GiaDien  ");
            rs = ps.executeQuery();
            while (rs.next()) {
                giadien[i] = Double.parseDouble(rs.getString("giaDien"));
                i += 1;
            }

        } catch (Exception e) {

        }
        if (csd <= 50) {
            t = csd * giadien[0];
        } else if (csd <= 100) {
            t = 50 * giadien[0] + (csd - 50) * giadien[1];
        } else if (csd <= 200) {
            t = 50 * giadien[0] + 50 * giadien[1] + (csd - 100) * giadien[2];
        } else if (csd <= 300) {
            t = 50 * giadien[0] + 50 * giadien[1] + (100) * giadien[2] + (csd - 200) * giadien[3];
        } else if (csd <= 400) {
            t = 50 * giadien[0] + 50 * giadien[1] + (100) * giadien[2] + (100) * giadien[3] + (csd - 300) * giadien[4];
        } else if (csd > 400) {
            t = 50 * giadien[0] + 50 * giadien[1] + (100) * giadien[2] + (100) * giadien[3] + (100) * giadien[4] + (csd - 400) * giadien[5];
        }

        return t.toString();
    }

    public String TinhTienNuoc(Double csn) {
        Double t = 0.0;
        int i = 0;
        Double giaNuoc[] = new Double[10];
        try {
            ps = connect.prepareStatement("select * from GiaNuoc");
            rs = ps.executeQuery();
            while (rs.next()) {
                giaNuoc[i] = Double.parseDouble(rs.getString("giaNuoc"));
                i += 1;
            }
        } catch (Exception e) {
        }
        if (csn <= 4) {
            t = csn * giaNuoc[0];
        } else if (csn <= 6) {
            t = 4 * giaNuoc[0] + (csn - 4) * giaNuoc[1];
        } else if (csn > 6) {
            t = 4 * giaNuoc[0] + 2 * giaNuoc[1] + (csn - 6) * giaNuoc[2];
        }

        return t.toString();
    }
    private void btnXuatHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatHDActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ReloadTbl();
        txtMTT.setText("");
        txtMKH.setText("");
        txtTenKH.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtCSDC.setText("");
        txtCSNC.setText("");
        txtCSDM.setText("");
        txtCSNM.setText("");
        txtSTTD.setText("");
        txtSTTN.setText("");
        txtTienDien.setText("");
        txtTienNuoc.setText("");
        btnTinhTien.setEnabled(false);
        btnLuu.setEnabled(false);
        btnXuatHD.setEnabled(false);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhTienDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB1;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXuatHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCSD;
    private javax.swing.JTextField txtCSDC;
    private javax.swing.JTextField txtCSDM;
    private javax.swing.JTextField txtCSNC;
    private javax.swing.JTextField txtCSNM;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMKH;
    private javax.swing.JTextField txtMTT;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSTTD;
    private javax.swing.JTextField txtSTTN;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienDien;
    private javax.swing.JTextField txtTienNuoc;
    // End of variables declaration//GEN-END:variables

}
